@baseUrl = http://localhost:3000

@token = {{authUser.response.body.token}}

@userId = 68eebaa0b7722a04553ce14f

GET {{baseUrl}}/health


### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "email": "romiro@gmail.com",
  "name": "Romiro",
  "pwd": "danger123456"
}

### Auth login com matricula admin
# @name authUser
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "romiro@gmail.com",
  "name": "Romiro",
  "pwd": "danger123456"
}

### Private routers

### Get users
# @name getUsers
GET {{baseUrl}}/user
Authorization: Bearer {{token}}

### Update user
# @name updateUser
PUT {{baseUrl}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "{{userId}}",
  "name": "New Name"
}


### Delete user
# @name deleteUser
DELETE {{baseUrl}}/user/{{userId}}
Authorization: Bearer {{token}}
Content-Type: application/json
