@baseUrl = http://localhost:3000

@token = {{authUser.response.body.token}}

GET {{baseUrl}}/health

### Get users
# @name getUser
GET {{baseUrl}}/user
Authorization: Bearer {{token}}

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "email": "romiro@gmail.com",
  "name": "Romiro",
  "pwd": "danger123456"
}

### Auth login com matricula admin
# @name authUser
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "romiro@gmail.com",
  "name": "Romiro",
  "pwd": "danger123456"
}
